resolve #23 Postモデルテストの実装
miracleave-ltd/mirameetVol28 pull request #56
Opened 2022-02-19 13:44 UTC by ryota-1231

## What
- Postモデルにおけるバリデーションテスト、意図したデータになるかのテストを実装
- Factorybotを導入
- Fakerの導入
- User、Postモデルのデモデータを用意

## Why
- Postモデルのデータ制御の信頼性を高めるため

2022-02-19 14:07 UTC, naomi-0913 requested changes
コメント追加しました！

2022-02-19 14:07 UTC, naomi-0913 commented on spec/post_spec.rb
> +    it '投稿が意図した内容で保存される' do
add_date_to_text のメソッドのテストをしているので、
it '#add_date_to_text' do とするのが正しい書き方かと思います。

2022-02-20 12:37 UTC, ryota-1231 commented on spec/post_spec.rb
> +    it '投稿が意図した内容で保存される' do
修正しました！

2022-02-20 12:46 UTC, naomi-0913 approved these changes
LGTM

2022-02-20 12:46 UTC, merged