resolve #62 結合テストの実装
miracleave-ltd/mirameetVol28 pull request #65
Opened 2022-02-27 14:02 UTC by ryota-1231

## What
- User/Devise/Post/Commentの主に内部結合のテスト実装
- エラー対応のため各viewファイルを修正
- deviseの日本語化のためにdevise.ja.ymlファイルを追加

## Why
- 結合テストを実装することでアプリケーションの機能の信頼性を向上させるため

2022-02-28 14:21 UTC, naomi-0913 requested changes
レビューしましたのでご確認お願いいたします！

2022-02-28 14:21 UTC, naomi-0913 commented on app/controllers/comments_controller.rb
> +    params.permit(:post_id).merge(params.require(:comment).permit(:text))
以下でもダメでしょうか？
params.permit(:post_id, comment: [:text])

2022-02-28 14:21 UTC, naomi-0913 commented on spec/requests/comments_controller_spec.rb
> +      it 'ログイン画面にリダイレクトされること' do
リクエストステータスのexampleは不要でしょうか？
(expect(response.status).to eq 302 のケース)

2022-02-28 14:21 UTC, naomi-0913 commented on spec/requests/posts_controller_spec.rb
> +      it 'リクエストが成功すること' do
レスポンスステータスが〇〇を返却すること
に修正お願いいたします。
他の同様のケースも同じく修正お願いします！

2022-02-28 14:21 UTC, naomi-0913 commented on spec/requests/posts_controller_spec.rb
> +      it '投稿が表示されていること' do
> 投稿が表示されていること

以下の表現の方がテスト内容と合致しているかと思いますが、いかがでしょうか？
レスポンスに投稿した内容を含むこと

他の同様のテストケースも修正お願いします！

2022-02-28 14:21 UTC, naomi-0913 commented on spec/requests/users_controller_spec.rb
> +        it 'ユーザー名が表示されること' do
投稿がある場合のテストケースを追加いただけますでしょうか？

2022-03-01 09:53 UTC, ryota-1231 commented on app/controllers/comments_controller.rb
> +    params.permit(:post_id).merge(params.require(:comment).permit(:text))
取れなかったので一旦現状のままでいかせてください。

2022-03-01 10:39 UTC, ryota-1231 commented on spec/requests/posts_controller_spec.rb
> +      it 'リクエストが成功すること' do
修正しました！
コミットNo: 28095ea289c1dcf61418730c9cae6f173695d0ae

2022-03-01 10:40 UTC, ryota-1231 commented on spec/requests/comments_controller_spec.rb
> +      it 'ログイン画面にリダイレクトされること' do
修正しました。

コミットNo: 3e2c2e09b71570cd7d2f1d3090d159f7c974e548

2022-03-01 11:55 UTC, naomi-0913 commented on app/controllers/comments_controller.rb
> +    params.permit(:post_id).merge(params.require(:comment).permit(:text))
承知しました！

2022-03-01 11:56 UTC, naomi-0913 commented on spec/requests/comments_controller_spec.rb
> +      it 'ログイン画面にリダイレクトされること' do
確認しました！OKです

2022-03-01 11:56 UTC, naomi-0913 commented on spec/requests/posts_controller_spec.rb
> +      it 'リクエストが成功すること' do
確認しました！OKです

2022-03-01 12:32 UTC, ryota-1231 commented on spec/requests/posts_controller_spec.rb
> +      it '投稿が表示されていること' do
修正しました！
コミットNo: cd27a570d610df10df5fcbb2642ddc00d3fa8890

2022-03-01 12:38 UTC, ryota-1231 commented on spec/requests/users_controller_spec.rb
> +        it 'ユーザー名が表示されること' do
修正しました！

コミットNo: daca5b6bd706f866dd74da66c761d266d38331b2

2022-03-02 10:16 UTC, naomi-0913 approved these changes
LGTM!

2022-03-02 11:32 UTC, merged