resolve #12 userコントローラの単体テストの実装
miracleave-ltd/mirameetVol28 pull request #66
Opened 2022-02-28 04:30 UTC by kobayashi-toshihiko

## What
- userコントローラの単体テストコードの実装

## Why
- 単体テストを実装することで、アプリケーションの機能チェック、及び品質の向上の為

2022-02-28 04:54 UTC, ryota-1231 commented
こちらテストは通りますか？rpsecコマンドを実行したらテストが落ちてしまいました。
何かコミット忘れなどないでしょうか？

2022-02-28 05:38 UTC, ryota-1231 requested changes

2022-02-28 05:38 UTC, ryota-1231 commented on spec/controllers/user_controller_spec.rb
> +RSpec.describe 'UsersControllers', type: :request do
今回の実装はControllerのテストです。Requestのテストではないと思います。

2022-02-28 05:38 UTC, ryota-1231 commented on spec/controllers/user_controller_spec.rb
> +        end
「リクエストが成功すること」を「200レスポンスを返すこと」に変更してください。さらに「正常にレスポンスを返すこと」を追加して、「be_successful」マッチャを使用してレスポンスが正しく返ってくることをテストしてください。

2022-02-28 05:38 UTC, ryota-1231 commented on spec/controllers/user_controller_spec.rb
> +        end
コントローラの単体テストの観点ではこちらは不要です。上層のRequest Specでテストします。

2022-02-28 05:38 UTC, ryota-1231 commented on spec/controllers/user_controller_spec.rb
> +        end
すいません。こちら僕のも直さないといけないのですが、「302レスポンスを返すこと」としてください。
さらに「ログイン画面へリダイレクトされること」を追加テストしてください。

2022-03-03 10:15 UTC, kobayashi-toshihiko commented on spec/controllers/user_controller_spec.rb
> +        end
修正しました。
コミットNo：094c58f8a263edd0cb2d52313db5a30884d720e6

2022-03-04 00:48 UTC, kobayashi-toshihiko commented on spec/controllers/user_controller_spec.rb
> +        end
ユーザ名、投稿表示のテストを削除しました。
commit 468e4d0bef122e87a466f5d5ca614d9970be2ee3

2022-03-04 02:48 UTC, kobayashi-toshihiko commented on spec/controllers/user_controller_spec.rb
> +RSpec.describe 'UsersControllers', type: :request do
Controllerのテストコードに修正しました。
commit 0b5d4e07efe74cbde3d66b162d1732e133654d3

2022-03-04 10:28 UTC, kobayashi-toshihiko commented on spec/controllers/user_controller_spec.rb
> +        end
「200レスポンスを返すこと」に変更、「be_successful」マッチャを使用してのテストコードを追加
commit 094c58f8a263edd0cb2d52313db5a30884d720e6

2022-03-04 12:13 UTC, kobayashi-toshihiko commented on spec/controllers/user_controller_spec.rb
> +        end
itの「302レスポンスを返すこと」に修正しました。
ログイン画面へリダイレクトされること」のテストコードを追加しました。
commit f31b0baa085f0752e8cf714975f4fd50141c4892

2022-03-04 12:15 UTC, kobayashi-toshihiko commented on spec/controllers/user_controller_spec.rb
> +        end
itの「302レスポンスを返すこと」に修正しました。
ログイン画面へリダイレクトされること」のテストコードを追加しました。
commit f31b0baa085f0752e8cf714975f4fd50141c4892

2022-03-04 13:28 UTC, ryota-1231 commented
user_controller_specとusers_controller_specが存在しています。修正をお願いします。

2022-03-05 02:48 UTC, kobayashi-toshihiko commented
user_controller_specを削除しました。
ご確認をお願いします。

2022-03-05 03:03 UTC, ryota-1231 commented on spec/controllers/user_controller_spec.rb
> +RSpec.describe 'UsersControllers', type: :request do
OKです！

2022-03-05 03:04 UTC, ryota-1231 commented on spec/controllers/user_controller_spec.rb
> +        end
OKです！

2022-03-05 03:10 UTC, ryota-1231 requested changes

2022-03-05 03:10 UTC, ryota-1231 commented on spec/rails_helper.rb
> +  config.include Devise::Test::ControllerHelpers, type: :controller
config.include Devise::Test::ControllerHelpers, type: :controller
が二つ存在しています。下の方を削除しておいてください。

2022-03-05 03:10 UTC, ryota-1231 commented on spec/controllers/users_controller_spec.rb
> +      let(:post_instance) { create(:post, user: user, text: 'PostTest', image: 'https://example_image_url') }
このpost_instanceは何に使用していますか？使用していないなら削除しましょう。

2022-03-05 03:10 UTC, ryota-1231 commented on spec/controllers/users_controller_spec.rb
> +          get :show, params: { id: user.id }
get :show, params: { id: user.id }が複数回登場しています。subjectとして共有化しましょう。

2022-03-05 03:23 UTC, kobayashi-toshihiko commented on spec/rails_helper.rb
> +  config.include Devise::Test::ControllerHelpers, type: :controller
Devise::Test::ControllerHelpersの重複分を削除しました。
commit ad365bb3f45b08ff57c2f4d26d07ca234e3a15ef

2022-03-05 03:32 UTC, kobayashi-toshihiko commented on spec/controllers/users_controller_spec.rb
> +      let(:post_instance) { create(:post, user: user, text: 'PostTest', image: 'https://example_image_url') }
post_instanceは使用していない為、削除
commit d5df8c774be2cae5b6d3ddeffb5eaf07c070d4a2

2022-03-05 03:45 UTC, kobayashi-toshihiko commented on spec/controllers/users_controller_spec.rb
> +          get :show, params: { id: user.id }
get :show, params: { id: user.id }の箇所は、subjectに変更
commit 0b9cae99639b39b0d57fc8590ad7f484b48a7572

2022-03-05 05:43 UTC, ryota-1231 commented on spec/controllers/users_controller_spec.rb
> +      let(:post_instance) { create(:post, user: user, text: 'PostTest', image: 'https://example_image_url') }
OK!

2022-03-05 05:43 UTC, ryota-1231 commented on spec/controllers/users_controller_spec.rb
> +          get :show, params: { id: user.id }
OK！

2022-03-05 05:43 UTC, ryota-1231 commented on spec/controllers/users_controller_spec.rb
> +      let(:post_instance) { create(:post, user: user, text: 'PostTest', image: 'https://example_image_url') }
OK!

2022-03-05 05:47 UTC, ryota-1231 commented on spec/rails_helper.rb
> +  config.include Devise::Test::ControllerHelpers, type: :controller
ものすごく細かくて申し訳ないのですが、上記の通り「下の方を削除」していただければと思います。

> config.include Devise::Test::IntegrationHelpers, type: :request
  config.include FactoryBot::Syntax::Methods
  config.include Devise::Test::ControllerHelpers, type: :controller

より

> config.include Devise::Test::ControllerHelpers, type: :controller
  config.include Devise::Test::IntegrationHelpers, type: :request
  config.include FactoryBot::Syntax::Methods

の方がまとまりが良いです。

三行の短いコードなのでそれほど影響ないですが、これが何十行にもなった時に Devise::Testが2回登場すると可読性が悪くなります。同じカテゴリーのものはまとめる習慣をつけていただければと思います。

2022-03-05 05:53 UTC, ryota-1231 requested changes

2022-03-05 05:53 UTC, ryota-1231 commented on spec/controllers/users_controller_spec.rb
> +      subject {get :show, params: { id: user.id }}
> subject {get :show, params: { id: user.id }}

{}の内側はスペースを一つずつ入れてください。

> subject { get :show, params: { id: user.id } }

またletでuserを定義していますが、呼び出し箇所がsubject内しかないため、変数にしなくていいと思います。
（変数にするのは複数箇所で呼び出して使い回ししたい時のみ）
userのデータの値を参照することもないため、nicknameを指定する必要もないです。

上記まとめると、
- subjectの{}のスペースを入れる
- let(:user)を削除
- subjectのuser.idを変数を使用せず直接createしたuserを使用する

2022-03-05 06:04 UTC, kobayashi-toshihiko commented on spec/rails_helper.rb
> +  config.include Devise::Test::ControllerHelpers, type: :controller
可読性の改善の為、カテゴリーでまとめてコード修正
commit ef9a1cdbc804d34c5f7e62a6e35c73c476c2fb04

2022-03-05 07:50 UTC, kobayashi-toshihiko commented on spec/controllers/users_controller_spec.rb
> +      subject {get :show, params: { id: user.id }}
[{}の内側はスペースを挿入して、修正
letの変数は、sign_in,sign_outの箇所で使用している為、nicknameの箇所のみ削除

commit 81612dd3aa0e96fa9558c6166a3c335ab67c14ca

2022-03-05 07:55 UTC, ryota-1231 approved these changes

2022-03-05 08:11 UTC, kobayashi-toshihiko commented
タスク完了

2022-03-05 08:20 UTC, merged