resolve #9 postコントローラの単体テストの実装
miracleave-ltd/mirameetVol28 pull request #73
Opened 2022-03-07 12:27 UTC by kobayashi-toshihiko

## What
- postコントローラの単体テストコードの実装

## Why
- 単体テストを実装することで、アプリケーションの機能チェック、及び品質の向上の為

2022-03-07 14:05 UTC, ryota-1231 requested changes

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +    context '投稿新規登録' do
ここのcontextは不要だと思います。create アクションのテストが投稿新規登録のテストだということがわかるからです。また、contextは状態を表す文言が入ります。例えば「ログインしている場合」というcontextはログインしている状態とも言い換えることができて状態を表しています。

ここ以外でももしあれば同様に対応お願いします。

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでpost_instanceをcreateしているのはなぜですか？

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +    subject { post :create, params: { post: { image: post_instance.image, text: post_instance.text } } }
パラメータのimage、とtextの値は文字列で指定してください。post_instancheをcreateしてその値を入れてまたcreateしてとなっています。余計なcreateは省きましょう。

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +    subject { patch :update, params: { id: post_instance.id, post: { image: post_instance.image, text: post_instance.text } } }
行数が長いので改行してください。

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでpost_instanceを呼び出しているのはなぜですか？

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでpost_instanceを呼び出しているのはなぜですか？

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでpost_instanceを呼び出しているのはなぜですか？

2022-03-07 14:05 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +  let(:user) { create(:user, nickname: 'kobato') }
userのテストはしないはずなのでnicknameは不要だと思います。

2022-03-08 11:48 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +    context '投稿新規登録' do
ありがとうございます。不要なcontextを削除しました。
他にも同様の箇所があったので、削除しました。
commit 40a3946ae55ae415c846b271c2cbc2400b17fd45

2022-03-08 12:18 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでのpost_instanceは不要でしたので、削除しました。
commit f2651ec72ba6b94eb09111c1fdf0ad7e051e4610

2022-03-08 12:19 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでのpost_instanceは不要の為、削除しました。
commit f2651ec72ba6b94eb09111c1fdf0ad7e051e4610

2022-03-08 12:19 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでのpost_instanceは不要の為、削除しました。
commit f2651ec72ba6b94eb09111c1fdf0ad7e051e4610

2022-03-08 12:20 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +          post_instance
ここでのpost_instanceは不要の為、削除しました。
commit f2651ec72ba6b94eb09111c1fdf0ad7e051e4610

2022-03-08 12:52 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +    subject { patch :update, params: { id: post_instance.id, post: { image: post_instance.image, text: post_instance.text } } }
行数を改行して修正しました。
commit 15768d8d8bc50cd70fd33d50c54e741a49dc78f3

2022-03-08 13:07 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +    subject { post :create, params: { post: { image: post_instance.image, text: post_instance.text } } }
ありがとうございます。パラメータのimage、とtextの値は文字列で指定して修正しました。
commit 937ca98de1bb12e9b165ddf817e08112ef7719df

2022-03-08 13:29 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +  let(:user) { create(:user, nickname: 'kobato') }
nicknameは不要の為、削除
commit d6a59151475656913ac34b6c2838aa5223ac4c9

2022-03-08 13:42 UTC, ryota-1231 requested changes

2022-03-08 13:42 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
> +  }
何が引数で何がメソッドなのか分かりづらいので下記のように訂正してください。

subject {
     patch :update, 
　 params: { 
       id: post_instance.id, 
       post: { image: post_instance.image, text: post_instance.text } 
     } 
  }

またインデントがおかしいので直してください。

2022-03-08 13:42 UTC, ryota-1231 commented on spec/controllers/posts_controller_spec.rb
>    let(:post_instance) { create(:post, user: user, text: 'PostRequestTest', image: 'https://example_image_url') }
post_instanceが必要ではない箇所が多いと思うのですが、この最上位で定義してしまうと、可読性が下がってしまいます。

下までテストを読み進めて行って「post_instanceって何だっけ？」ってなったとき一番上まで探しに行かないといけないので見づらいです。必要なところで定義して、必要なところから呼び出してください。

2022-03-09 11:00 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +  }
上記の例に従い、subjectのリファクタリングを行いました。
commit 03f60303a7faf3ac89240fe2e1a607b1b56fd582

2022-03-09 11:19 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
>    let(:post_instance) { create(:post, user: user, text: 'PostRequestTest', image: 'https://example_image_url') }
可読性の指摘、ありがとうございます。必要な箇所で定義をし直し、修正しました
commit da2601dc00ac6013a003f0b99b21fe2625bd0eef

2022-03-09 11:20 UTC, kobayashi-toshihiko commented on spec/controllers/posts_controller_spec.rb
> +  }
再度、インデントの修正をしました。
commit da2601dc00ac6013a003f0b99b21fe2625bd0eef

2022-03-09 11:32 UTC, ryota-1231 approved these changes

2022-03-09 11:35 UTC, merged