resolve #47 AWS cloudformationVPC構築
miracleave-ltd/mirameetVol28 pull request #83
Opened 2022-03-28 01:16 UTC by kobayashi-toshihiko

## What
- cloudformationVPC構築

## Why
- cloudformationよって、効率的に自動基盤構築をする為

2022-03-28 01:20 UTC, kobayashi-toshihiko commented
## スタックの作成のやり方
- サービスからCloudFormationを選択
左ペインから「スタックを選択」 「スタックの作成」をクリック→「新しいリソースを使用(標準)」 前提条件 - テンプレートの準備
	「テンプレートの準備完了」にチェック
テンプレートの指定
	「テンプレートファイルのアップロード」にチェック
	vpc.ymlを選択
「次へ」をクリック

- スタックの名前
	※任意の名前を入力 (例)vpc-stack
「次へ」をクリック
そのまま「次へ」をクリック
「スタックの作成」をクリック
ステータスが「CREATE_COMPLETE」になったらOK
※イベントタブで進捗がリアルタイムで閲覧できる

## スタックの削除のやり方
※削除する場合は、スタックの削除によって一括で削除できる
- 削除したいスタックを選択
「削除」をクリック
「スタックの削除」をクリック
スタック一覧から消えればOK

2022-03-31 02:05 UTC, naomi-0913 requested changes
作成ありがとうございます！
スタックは両方ともCREATE_COMPLETEしました！
インターネットの接続ができないので、修正お願いできますか？

2022-03-31 02:05 UTC, naomi-0913 commented on vpc.yml
> +  VPC:
EIPがないです。

2022-03-31 02:05 UTC, naomi-0913 commented on vpc.yml
> +
NatGateWayを追加いただけますか？（プライベートルートも含めて）

2022-03-31 05:32 UTC, kobayashi-toshihiko commented on vpc.yml
> +  VPC:
EIPを追加しました。

2022-03-31 05:35 UTC, kobayashi-toshihiko commented on vpc.yml
> +
Natゲートウェイを追加しました。privateSubnetAに対して、Nat向けルーティング設定をしました。
commit c12c0aec9dcd1d31ea138387c331fa1701135c16

2022-04-03 08:05 UTC, naomi-0913 approved these changes
動作確認しました！CodeBuildとの連携も出来たのでLGTMです！

2022-04-03 08:11 UTC, merged